# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.

require 'cucumber/rails'
require 'webmock'
require 'cucumber/rspec/doubles'
require "capybara/cuprite"
require 'database_cleaner/active_record'
require_relative './page_objects/base_page'
Dir[File.dirname(__FILE__) + '/page_objects/**/*.rb'].each { |f| require f }

# frozen_string_literal: true

# Add time travel support
World(ActiveSupport::Testing::TimeHelpers)

# Capybara defaults to CSS3 selectors rather than XPath.
# If you'd prefer to use XPath, just uncomment this line and adjust any
# selectors in your step definitions to use the XPath syntax.
# Capybara.default_selector = :xpath

# By default, any exception happening in your Rails application will bubble up
# to Cucumber so that your scenario will fail. This is a different from how
# your application behaves in the production environment, where an error page will
# be rendered instead.
#
# Sometimes we want to override this default behaviour and allow Rails to rescue
# exceptions and display an error page (just like when the app is running in production).
# Typical scenarios where you want to do this is when you test your error pages.
# There are two ways to allow Rails to rescue exceptions:
#
# 1) Tag your scenario (or feature) with @allow-rescue
#
# 2) Set the value below to true. Beware that doing this globally is not
# recommended as it will mask a lot of errors for you!
#
ActionController::Base.allow_rescue = false

Capybara.server = :puma
Selenium::WebDriver.logger.output = false
Capybara.default_driver = :cuprite
Capybara.javascript_driver = :cuprite

Capybara.register_driver(:cuprite) do |app|
  Capybara::Cuprite::Driver.new(
    app,
    timeout: 10,
    window_size: [1920, 1080],
    headless: ENV['SHOW_BROWSER'].nil?,
    inspector: true,
    pending_connection_errors: false
  )
end

Capybara.default_normalize_ws = true
Capybara.default_max_wait_time = 10

# Remove/comment out the lines below if your app doesn't have a database.
# For some databases (like MongoDB and CouchDB) you may need to use :truncation instead.
begin
  DatabaseCleaner.strategy = :transaction
rescue NameError
  raise "You need to add database_cleaner to your Gemfile (in the :test group) if you wish to use it."
end

Around do |scenario, block|
  DatabaseCleaner.cleaning(&block)
end

After do
  # in case we forget to set time back
  travel_back
  # Rails.application.config.prl_opening_date = Date.today + 1.day
end

Before do
  uploaded_files = []

  s3_client = instance_double(Aws::S3::Client)
  allow(Aws::S3::Client).to receive(:new).and_return s3_client

  allow(s3_client).to receive(:put_object) do |args|
    put_object = double('put_object', etag: 'filename', key: args[:key], last_modified: Time.current)
    uploaded_files << put_object
    put_object
  end

  allow(s3_client).to receive(:list_objects) do |args|
    matches = uploaded_files.select { |file| file.key.start_with?(args[:prefix]) }
    double('object', contents: matches, empty?: matches.empty?)
  end

  allow(Aws::AssumeRoleWebIdentityCredentials).to receive(:new).with(
    role_arn: ENV['AWS_ROLE_ARN'],
    web_identity_token_file: ENV['AWS_WEB_IDENTITY_TOKEN_FILE']
  )

end


# Possible values are :truncation and :transaction
# The :transaction strategy is faster, but might give you threading problems.
# See https://github.com/cucumber/cucumber-rails/blob/master/features/choose_javascript_database_strategy.feature
Cucumber::Rails::Database.javascript_strategy = :truncation
