require: rubocop-performance

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - './*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'lib/tasks/**/*'
    - 'lib/generators/**/*'
    - 'features/**/*'
    - 'spec/**/*'
    - 'vendor/**/*'

####################################
## Customization for this project ##
####################################

ClassLength:
  Max: 105

LineLength:
  Max: 130

MethodLength:
  Max: 21

AbcSize:
  Max: 24

CyclomaticComplexity:
  Max: 12

Documentation:
  Enabled: false

Performance/RedundantMerge:
  Enabled: false

FrozenStringLiteralComment:
  Enabled: false

SymbolArray:
  Enabled: false

SpaceInsideHashLiteralBraces:
  Enabled: false

PredicateName:
  Enabled: false

MultilineIfModifier:
  Enabled: false

AlignHash:
  Enabled: false

IfUnlessModifier:
  Enabled: false

StringLiterals:
  Enabled: false

TrailingCommaInArrayLiteral:
  Enabled: false

TrailingCommaInHashLiteral:
  Enabled: false

TrailingCommaInArguments:
  Enabled: false

MultilineMethodCallIndentation:
  Enabled: false

EmptyLineAfterGuardClause:
  Enabled: false

RescuedExceptionsVariableName:
  Enabled: false

MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required

MissingRespondToMissing:
  Exclude:
    - app/presenters/c8_confidentiality_presenter.rb
