plugins:
  - rubocop-performance

AllCops:
  SuggestExtensions: false
  NewCops: disable
  TargetRubyVersion: 4.0.0
  Exclude:
    - './*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'lib/tasks/**/*'
    - 'lib/generators/**/*'
    - 'features/**/*'
    - 'spec/**/*'
    - 'vendor/**/*'
    - 'config/routes.rb'


####################################
## Customization for this project ##
####################################

Metrics/ClassLength:
  Max: 105
  Exclude:
    - app/models/document_upload.rb
    - app/services/c100_app/opening_decision_tree.rb

Layout/LineLength:
  Max: 130

Metrics/MethodLength:
  Max: 21

Metrics/CyclomaticComplexity:
  Max: 12

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Naming/PredicatePrefix:
  Enabled: false

Style/MultilineIfModifier:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required

Style/MissingRespondToMissing:
  Exclude:
    - app/presenters/c8_confidentiality_presenter.rb

Style/AccessorGrouping:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Style/CaseLikeIf:
  Enabled: false

Style/HashAsLastArrayItem:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/SoleNestedConditional:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Metrics/AbcSize:
  Max: 24.5
  Exclude:
    - app/controllers/documents_controller.rb

# Performance/RedundantMerge:
#   Enabled: false
