require: rubocop-performance

AllCops:
  SuggestExtensions: false
  NewCops: disable
  TargetRubyVersion: 2.7
  Exclude:
    - './*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'lib/tasks/**/*'
    - 'lib/generators/**/*'
    - 'features/**/*'
    - 'spec/**/*'
    - 'vendor/**/*'


####################################
## Customization for this project ##
####################################

Metrics/ClassLength:
  Max: 105
  Exclude:
    - app/models/document_upload.rb

Layout/LineLength:
  Max: 130

Metrics/MethodLength:
  Max: 21

Metrics/CyclomaticComplexity:
  Max: 12

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Style/MultilineIfModifier:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required

Style/MissingRespondToMissing:
  Exclude:
    - app/presenters/c8_confidentiality_presenter.rb

Style/AccessorGrouping:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Style/CaseLikeIf:
  Enabled: false

Style/HashAsLastArrayItem:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/SoleNestedConditional:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Metrics/AbcSize:
  Max: 24.5

# Performance/RedundantMerge:
#   Enabled: false




Performance/AncestorsInclude:
  Enabled: false

Performance/ArraySemiInfiniteRangeSlice:
  Enabled: false

Performance/BigDecimalWithNumericArgument:
  Enabled: false

Performance/BindCall:
  Enabled: false

Performance/BlockGivenWithExplicitBlock:
  Enabled: false

Performance/Caller:
  Enabled: false

Performance/CaseWhenSplat:
  Enabled: false

Performance/Casecmp:
  Enabled: false

Performance/ChainArrayAllocation:
  Enabled: false

Performance/CollectionLiteralInLoop:
  Enabled: false

Performance/CompareWithBlock:
  Enabled: false

Performance/ConcurrentMonotonicTime:
  Enabled: false

Performance/ConstantRegexp:
  Enabled: false

Performance/Count:
  Enabled: false

Performance/DeletePrefix:
  Enabled: false

Performance/DeleteSuffix:
  Enabled: false

Performance/Detect:
  Enabled: false

Performance/DoubleStartEndWith:
  Enabled: false

Performance/EndWith:
  Enabled: false

Performance/FixedSize:
  Enabled: false

Performance/FlatMap:
  Enabled: false

Performance/InefficientHashSearch:
  Enabled: false

Performance/IoReadlines:
  Enabled: false

Performance/MapCompact:
  Enabled: false

Performance/MethodObjectAsBlock:
  Enabled: false

Performance/OpenStruct:
  Enabled: false

Performance/RangeInclude:
  Enabled: false

Performance/RedundantBlockCall:
  Enabled: false

Performance/RedundantEqualityComparisonBlock:
  Enabled: false

Performance/RedundantMatch:
  Enabled: false

Performance/RedundantMerge:
  Enabled: false

Performance/RedundantSortBlock:
  Enabled: false

Performance/RedundantSplitRegexpArgument:
  Enabled: false

Performance/RedundantStringChars:
  Enabled: false

Performance/RegexpMatch:
  Enabled: false

Performance/ReverseEach:
  Enabled: false

Performance/ReverseFirst:
  Enabled: false

Performance/SelectMap:
  Enabled: false

Performance/Size:
  Enabled: false

Performance/SortReverse:
  Enabled: false

Performance/Squeeze:
  Enabled: false

Performance/StartWith:
  Enabled: false

Performance/StringIdentifierArgument:
  Enabled: false

Performance/StringInclude:
  Enabled: false

Performance/StringReplacement:
  Enabled: false

Performance/Sum:
  Enabled: false

Performance/TimesMap:
  Enabled: false

Performance/UnfreezeString:
  Enabled: false

Performance/UriDefaultParser:
  Enabled: false
