language: ruby

addons:
  postgresql: "9.5"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - git remote set-branches origin master && git fetch

script:
  - bundle exec rake travis
