# Simplify running the application inside a container locally.
# Usage: `docker-compose up`
#
# Do not use docker-compose in production environments.
#
version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres@db/c100-application
      - EXTERNAL_URL=http://localhost:3000
      - RAILS_SERVE_STATIC_FILES=1
      - DATABASE_SSLMODE=disable
      - DISABLE_HTTPS=1
    ports:
      - "3000:3000"
    depends_on:
      - db
