# Add court slugs to the blocklist if they do not process online payments.
#
# Courts without a GBS code will not receive online payments, no need
# to add these to the blocklist.

blocklist:
  - blocklisted-slug-example

  # Batch 3 - due 17/09/2020
  #
  - york-county-court-and-family-court
  - barrow-in-furness-county-court-and-family-court
  - liverpool-civil-and-family-court

  # Following slugs to be removed in 3 weeks. All these had their GBS code
  # previously set, and now it has been unset, but existing applications
  # in our database will still have it for a while.
  #
  - canterbury-combined-court-centre
  - carmarthen-county-court-and-family-court
  - chester-civil-and-family-justice-centre
  - clerkenwell-and-shoreditch-county-court-and-family-court
  - crewe-county-court-and-family-court
  - dartford-county-court-and-family-court
  - dudley-county-court-and-family-court
  - haverfordwest-county-court-and-family-court
  - hertford-county-court-and-family-court
  - isle-of-wight-combined-court
  - maidstone-combined-court-centre
  - staines-county-court-and-family-court
  - thanet-county-court-and-family-court
  - torquay-and-newton-abbot-county-court-and-family-court
  - uxbridge-county-court-and-family-court
  - weymouth-combined-court
  - yeovil-county-family-and-magistrates-court
