# Add court slugs to the blocklist if they do not process online payments.
#
# Courts without a GBS code will not receive online payments, no need
# to add these to the blocklist.

blocklist:
  - blocklisted-slug-example
  - preston-crown-court-and-family-court-sessions-house
  - manchester-civil-justice-centre-civil-and-family-courts
  - newcastle-civil-family-courts-and-tribunals-centre
  - bournemouth-and-poole-county-court-and-family-court
  - york-county-court-and-family-court
  - barrow-in-furness-county-court-and-family-court
  - liverpool-civil-and-family-court
